### PR TITLE
Comment editing (fixes #26)

### LINKED ISSUE #26: Implement comment editing
Comments should be editable by their original posters and by anyone with moderation access.

### PR DESCRIPTION
**Pull request by jboning**

### CODE REVIEW

**Comment by amcgregor** [comment]
This is a substantial change set that I'll need to test before merging.

**Comment by jboning** [comment]
Just discovered problem: editing the original comment in a thread causes live update to destroy the thread title (even on reloads, since the notification system replays recent notifications to new clients).

**Comment by jboning** [comment]
Failure message and the bug that I noticed earlier are fixed, I think this is ready for inspection now!

**Comment by jboning** [comment]
With this change, styling is a little off on the create discussion input form. Will into.

**Comment by lizthegrey** [comment]
UI is checking for whether or not someone is a moderator/admin to show them the edit button, but actual editing currently appears to require admin permissions.

```
    if not (user and (user.admin or user._current_obj() == self.comment.creator)):
```

**Pull request merged**
