### PR TITLE
Shitty Mobile Fix

### PR DESCRIPTION
**Pull request by ghost**
Needs some CSS to go with it, merge with whatever's the work branch

### CODE REVIEW

**Comment by jboning** [comment]
I confess to not understanding. I thought the col values were supposed to add up to some constant? Do I just need to read up more on bootstrap?

**Comment by ghost** [comment]
They're part of the responsive design grid; 12 makes one row. The xs/sm/md/ld values specify for what document width (and up until another rule overrides it) the rule applies to. So bascially I've made the content 10/12 of the screen instead of 7/12 on devices while moving avatars and usernames in their own row below 768px for the viewport.

**Comment by ghost** [comment]
And here are the docs for that: http://getbootstrap.com/css/#grid

**Comment by jboning** [comment]
I see. Yeah, this seems reasonable. Not beautiful yet but strictly a usability improvement, I think, so I will go ahead and merge!

**Pull request merged**
